name: memorial_book
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.5
  provider: ^6.1.1
  animated_splash_screen: ^1.3.0
  flutter_multi_formatter: ^2.2.1
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.0.17
  loading_indicator: ^3.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  sizer: ^2.0.15
  firebase_messaging: ^14.3.0
  firebase_core: ^2.8.0
  flutter_local_notifications: ^13.0.0
  country_codes: ^2.2.0
  device_info_plus: ^8.0.0
  flutter_svprogresshud: ^1.0.0
  image_picker: ^1.0.4
  file_picker: ^5.3.1
  location: ^5.0.3
  flutter_geocoder: ^0.2.2-nullsafety
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1
  share_plus: ^7.2.1
  flutter_email_sender: ^6.0.2
  url_launcher: ^6.2.2
  uri_to_file: ^1.0.0
  flutter_animator: ^3.2.2
  carousel_slider: ^4.2.1
  galleryimage: ^2.0.1
  animated_flip_counter: ^0.3.3
  gradient_progress_indicator: ^1.0.0+5
  badges: ^3.1.2
  flutter_progress_hud: ^2.0.2
  animate_do: ^3.3.4
  photo_view: ^0.15.0
  auto_size_text: ^3.0.0
  flutter_animated_icons: ^1.0.1
  lottie: ^1.4.3

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: "assets/images/splashScreenImage.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/appIconImage.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/latoRegular.ttf
    - family: LatoBold
      fonts:
        - asset: assets/fonts/latoBold.ttf
    - family: LatoBlack
      fonts:
        - asset: assets/fonts/latoBlack.ttf
    - family: LatoSemiBold
      fonts:
        - asset: assets/fonts/LatoSemiBold.ttf

flutter_intl:
  enabled: true
  main_locale: ru